module.exports = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: [
      'db',
      'mp3',
      'ttf',
      'png',
      'jpg',
      'otf',
      'obj',
      'bin',
      'txt',
      'mtl',
      'JPG',
      'vrx',
      'hdr',
      'gltf',
      'glb',
      'bmp',
      'gif',
      'ico',
      'tif',
      'tga',
      'mov',
      'cur',
    ],
    sourceExts: ['jsx', 'mjs', 'js', 'json', 'ts', 'tsx', 'svg'],
  },
};
